kind: pipeline
type: exec
name: default

platform:
  os: linux
  arch: arm64

steps:
  - name: deploy
    environment:
      BASE_URL:
        from_secret: BASE_URL
      API_KEY:
        from_secret: API_KEY
    commands:
      - echo BASE_URL=$BASE_URL > .env
      - echo API_KEY=$API_KEY >> .env
      - cat .env
      - docker compose up -d --build --force-recreate
      - docker system prune -f -a
